chrome:
  driver:
    location: /Users/qianhao.zhou/tools/chromedriver
    poolSize: 1

rruu.url: http://www.rruu.com/new_zealand/185.html

tff.url: https://items.alitrip.com/item.htm?spm=a230r.1.14.1.vBJEzs&id=521354623106&ns=1&abbucket=8