chrome:
  driver:
    location: /Users/qianhao.zhou/tools/chromedriver
    poolSize: 1

spring:
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nztrip?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: Initial2
    type: com.zaxxer.hikari.HikariDataSource
    initialize: false